# Generated by Django 4.2.30 on 2026-07-22 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shelfbook',
            unique_together={('shelf', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('user', 'name')},
        ),
    ]
